# Generated by Django 4.1.5 on 2024-01-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_certifications_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='open_source_link',
        ),
    ]
