# Generated by Django 4.1.5 on 2024-02-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('github', models.URLField(blank=True)),
                ('demo', models.URLField(blank=True)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
