# Generated by Django 4.1.5 on 2024-02-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_otherprojects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherProjects',
            new_name='OtherProject',
        ),
    ]
