# Generated by Django 4.1.5 on 2024-02-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_otherprojects_otherproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherproject',
            name='proj_lang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='proj_lang',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
