# Generated by Django 4.1.5 on 2024-02-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
