# Generated by Django 4.1.5 on 2024-02-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_start_date_experience_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='date',
            new_name='start_date',
        ),
    ]
