# Generated by Django 4.1.5 on 2024-02-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_experience_programming_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programming_experience',
            name='proficiency',
        ),
    ]
