# Generated by Django 4.1.5 on 2024-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_programming_experience_proficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programming_Experience_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
