# Generated by Django 5.0.3 on 2024-03-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_programming_experience_extra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievement',
        ),
        migrations.RenameModel(
            old_name='Certifications',
            new_name='Certification',
        ),
    ]
