name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install certifi
        pip install pillow
        pip install django
        pip install django-rest-framework
        pip install contourpy
        pip install cffi
        pip install asgiref
        pip install charset-normalizer
        pip install colorama
        pip install cors
        pip install filelock
        pip install future
        pip install gevent
        pip install greenlet
        pip install idna
        pip install numpy
        pip install pycparser
        pip install PySocks
        pip install pytz
        pip install requests
        pip install requests-file
        pip install setuptools
        pip install sqlparse
        pip install tldextract
        pip install tzdata
        pip install urllib3
        pip install zope.event
        pip install zope.interface
        pip install django-cors-headers
       
        
    - name: Run Tests
      run: |
        python manage.py test
